// Inherit the parent event
event_inherited();

dialog.add(spr_ANGRY, "I AM VERY ANGRY!!!")
dialog.add(spr_Player, "hi i am the player :DDD")
dialog.add(spr_ANGRY, "I AM GOING TO FUCKING MURDER YOU RAAHHHHH!!!!!11!!1!!!!1111!1!")
dialog.add(spr_Player, "aaaa help me D::")
dialog.add(spr_ANGRY, "RAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHHHHHHHHH")